/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with API info.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login and get JWT tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh access token using refresh token.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current user information.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a CSV file for processing.
         *
         *     The file will be parsed, validated, and stored in the database.
         *     Activity data will be extracted and made available for analysis.
         */
        post: operations["upload_file_api_v1_files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description List all uploaded files.
         */
        get: operations["list_files_api_v1_files_get"];
        put?: never;
        post?: never;
        /**
         * Delete All Files
         * @description Delete all files from the database (admin only).
         *
         *     Optionally filter by status (e.g., 'failed' to delete only failed files).
         */
        delete: operations["delete_all_files_api_v1_files_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Get file metadata by ID.
         */
        get: operations["get_file_api_v1_files__file_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete File
         * @description Delete a file and its associated data.
         */
        delete: operations["delete_file_api_v1_files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File Dates
         * @description Get available dates for a file.
         */
        get: operations["get_file_dates_api_v1_files__file_id__dates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Data Directory
         * @description Start a background scan of the data directory for CSV files.
         *
         *     Only admins can trigger a scan. Files already in the database are skipped.
         *     Returns immediately with scan status - poll GET /scan/status for progress.
         */
        post: operations["scan_data_directory_api_v1_files_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/scan/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Status
         * @description Get the current status of the background file scan.
         *
         *     Poll this endpoint to track import progress.
         */
        get: operations["get_scan_status_api_v1_files_scan_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/watcher/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watcher Status
         * @description Get the current status of the automatic file watcher.
         *
         *     The file watcher monitors the data directory for new CSV files
         *     and automatically ingests them into the database.
         */
        get: operations["get_watcher_status_api_v1_files_watcher_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/{file_id}/{analysis_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity Data
         * @description Get activity data for a specific file and date.
         *
         *     Returns data in columnar format for efficient transfer.
         *     The view window starts from analysis_date at 12:00 (noon) and extends for view_hours.
         */
        get: operations["get_activity_data_api_v1_activity__file_id___analysis_date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/{file_id}/{analysis_date}/sadeh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity Data With Sadeh
         * @description Get activity data with Sadeh algorithm results.
         *
         *     Returns data with pre-calculated sleep scoring (1=sleep, 0=wake).
         */
        get: operations["get_activity_data_with_sadeh_api_v1_activity__file_id___analysis_date__sadeh_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Markers
         * @description Get all markers for a specific file and date.
         *
         *     Returns sleep markers, nonwear markers, and calculated metrics.
         *     Optionally includes algorithm results for overlay display.
         */
        get: operations["get_markers_api_v1_markers__file_id___analysis_date__get"];
        /**
         * Save Markers
         * @description Save markers for a specific file and date.
         *
         *     Replaces all existing markers for this file/date with the new ones.
         *     Triggers background calculation of sleep metrics.
         */
        put: operations["save_markers_api_v1_markers__file_id___analysis_date__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}/{period_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Marker
         * @description Delete a specific marker period.
         */
        delete: operations["delete_marker_api_v1_markers__file_id___analysis_date___period_index__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markers/{file_id}/{analysis_date}/table/{period_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Onset Offset Data
         * @description Get activity data around a marker for onset/offset tables.
         *
         *     Returns data points within window_minutes of the onset and offset timestamps.
         */
        get: operations["get_onset_offset_data_api_v1_markers__file_id___analysis_date__table__period_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityDataColumnar
         * @description Columnar format for efficient JSON transfer.
         *
         *     This format reduces JSON overhead by using arrays instead of
         *     repeated object keys for each data point.
         */
        ActivityDataColumnar: {
            /**
             * Timestamps
             * @description Unix timestamps
             */
            timestamps?: number[];
            /** Axis X */
            axis_x?: number[];
            /** Axis Y */
            axis_y?: number[];
            /** Axis Z */
            axis_z?: number[];
            /** Vector Magnitude */
            vector_magnitude?: number[];
        };
        /**
         * ActivityDataResponse
         * @description Response for activity data endpoint.
         */
        ActivityDataResponse: {
            data: components["schemas"]["ActivityDataColumnar"];
            /** Available Dates */
            available_dates?: string[];
            /**
             * Current Date Index
             * @default 0
             */
            current_date_index: number;
            /** Algorithm Results */
            algorithm_results?: number[] | null;
            /** File Id */
            file_id: number;
            /** Analysis Date */
            analysis_date: string;
            /** View Start */
            view_start?: number | null;
            /** View End */
            view_end?: number | null;
        };
        /**
         * AlgorithmType
         * @description Sleep scoring algorithm identifiers.
         *
         *     These values match the algorithm IDs registered in AlgorithmFactory.
         * @enum {string}
         */
        AlgorithmType: "sadeh_1994_original" | "sadeh_1994_actilife" | "cole_kripke_1992_original" | "cole_kripke_1992_actilife" | "manual";
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_file_api_v1_files_upload_post */
        Body_upload_file_api_v1_files_upload_post: {
            /**
             * File
             * Format: binary
             * @description CSV file to upload
             */
            file: string;
        };
        /**
         * FileInfo
         * @description File metadata for listing.
         */
        FileInfo: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Original Path */
            original_path?: string | null;
            /**
             * File Type
             * @default csv
             */
            file_type: string;
            /** @default pending */
            status: components["schemas"]["FileStatus"];
            /** Row Count */
            row_count?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Uploaded By Id */
            uploaded_by_id?: number | null;
            /** Uploaded At */
            uploaded_at?: string | null;
        };
        /**
         * FileListResponse
         * @description Response for file listing endpoint.
         */
        FileListResponse: {
            /** Files */
            files: components["schemas"]["FileInfo"][];
            /** Total */
            total: number;
        };
        /**
         * FileStatus
         * @description File processing status.
         * @enum {string}
         */
        FileStatus: "pending" | "processing" | "ready" | "failed";
        /**
         * FileUploadResponse
         * @description Response after file upload.
         */
        FileUploadResponse: {
            /** File Id */
            file_id: number;
            /** Filename */
            filename: string;
            status: components["schemas"]["FileStatus"];
            /** Row Count */
            row_count?: number | null;
            /**
             * Message
             * @default File uploaded successfully
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ManualNonwearPeriod
         * @description Individual manual nonwear period with timestamps.
         *
         *     Ported from desktop's dataclasses_markers.ManualNonwearPeriod.
         */
        ManualNonwearPeriod: {
            /** Start Timestamp */
            start_timestamp?: number | null;
            /** End Timestamp */
            end_timestamp?: number | null;
            /**
             * Marker Index
             * @default 1
             */
            marker_index: number;
            /** @default manual */
            source: components["schemas"]["NonwearDataSource"];
        };
        /**
         * MarkerCategory
         * @description Category of marker for styling and routing.
         * @enum {string}
         */
        MarkerCategory: "sleep" | "nonwear";
        /**
         * MarkerType
         * @description Sleep marker type classifications.
         * @enum {string}
         */
        MarkerType: "MAIN_SLEEP" | "NAP";
        /**
         * MarkerUpdateRequest
         * @description Request to update markers for a file/date.
         */
        MarkerUpdateRequest: {
            /** Sleep Markers */
            sleep_markers?: components["schemas"]["SleepPeriod"][] | null;
            /** Nonwear Markers */
            nonwear_markers?: components["schemas"]["ManualNonwearPeriod"][] | null;
            algorithm_used?: components["schemas"]["AlgorithmType"] | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * MarkersWithMetricsResponse
         * @description Response with markers and their calculated metrics.
         */
        MarkersWithMetricsResponse: {
            /** Sleep Markers */
            sleep_markers?: components["schemas"]["SleepPeriod"][];
            /** Nonwear Markers */
            nonwear_markers?: components["schemas"]["ManualNonwearPeriod"][];
            /** Metrics */
            metrics?: components["schemas"]["SleepMetrics"][];
            /** Algorithm Results */
            algorithm_results?: number[] | null;
            /** @default draft */
            verification_status: components["schemas"]["VerificationStatus"];
            /** Last Modified At */
            last_modified_at?: string | null;
            /**
             * Is Dirty
             * @default false
             */
            is_dirty: boolean;
        };
        /**
         * NonwearDataSource
         * @description Nonwear data source types.
         * @enum {string}
         */
        NonwearDataSource: "choi_algorithm" | "manual";
        /**
         * OnsetOffsetDataPoint
         * @description Single data point for onset/offset tables.
         */
        OnsetOffsetDataPoint: {
            /** Timestamp */
            timestamp: number;
            /** Datetime Str */
            datetime_str: string;
            /** Axis Y */
            axis_y: number;
            /** Vector Magnitude */
            vector_magnitude: number;
            /** Algorithm Result */
            algorithm_result?: number | null;
        };
        /**
         * OnsetOffsetTableResponse
         * @description Response with data points around a marker for tables.
         */
        OnsetOffsetTableResponse: {
            /** Onset Data */
            onset_data?: components["schemas"]["OnsetOffsetDataPoint"][];
            /** Offset Data */
            offset_data?: components["schemas"]["OnsetOffsetDataPoint"][];
            /** Period Index */
            period_index: number;
        };
        /**
         * SaveStatusResponse
         * @description Response after saving markers.
         */
        SaveStatusResponse: {
            /** Success */
            success: boolean;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /** Sleep Marker Count */
            sleep_marker_count: number;
            /** Nonwear Marker Count */
            nonwear_marker_count: number;
            /**
             * Message
             * @default Markers saved successfully
             */
            message: string;
        };
        /**
         * SleepMetrics
         * @description Complete sleep quality metrics for a single sleep period.
         *
         *     Implements Tudor-Locke metrics algorithm as defined in the
         *     actigraph.sleepr R package.
         *
         *     Reference:
         *         Tudor-Locke C, et al. (2014). Fully automated waist-worn accelerometer algorithm
         *         for detecting children's sleep-period time. Applied Physiology, Nutrition, and
         *         Metabolism, 39(1):53-57.
         */
        SleepMetrics: {
            /** In Bed Time */
            in_bed_time?: string | null;
            /** Out Bed Time */
            out_bed_time?: string | null;
            /** Sleep Onset */
            sleep_onset?: string | null;
            /** Sleep Offset */
            sleep_offset?: string | null;
            /** Time In Bed Minutes */
            time_in_bed_minutes?: number | null;
            /** Total Sleep Time Minutes */
            total_sleep_time_minutes?: number | null;
            /** Sleep Onset Latency Minutes */
            sleep_onset_latency_minutes?: number | null;
            /** Waso Minutes */
            waso_minutes?: number | null;
            /** Number Of Awakenings */
            number_of_awakenings?: number | null;
            /** Average Awakening Length Minutes */
            average_awakening_length_minutes?: number | null;
            /** Sleep Efficiency */
            sleep_efficiency?: number | null;
            /** Movement Index */
            movement_index?: number | null;
            /** Fragmentation Index */
            fragmentation_index?: number | null;
            /** Sleep Fragmentation Index */
            sleep_fragmentation_index?: number | null;
            /** Total Activity */
            total_activity?: number | null;
            /** Nonzero Epochs */
            nonzero_epochs?: number | null;
        };
        /**
         * SleepPeriod
         * @description Individual sleep period with onset/offset timestamps.
         *
         *     Ported from desktop's dataclasses_markers.SleepPeriod.
         */
        SleepPeriod: {
            /** Onset Timestamp */
            onset_timestamp?: number | null;
            /** Offset Timestamp */
            offset_timestamp?: number | null;
            /**
             * Marker Index
             * @default 1
             */
            marker_index: number;
            /** @default MAIN_SLEEP */
            marker_type: components["schemas"]["MarkerType"];
        };
        /**
         * Token
         * @description JWT token response.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TokenRefresh
         * @description Token refresh request.
         */
        TokenRefresh: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * UserCreate
         * @description User creation request.
         */
        UserCreate: {
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default annotator
             */
            role: string;
        };
        /**
         * UserRead
         * @description User response model.
         */
        UserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /**
             * Role
             * @default annotator
             */
            role: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationStatus
         * @description Verification status for annotations.
         * @enum {string}
         */
        VerificationStatus: "draft" | "submitted" | "verified" | "disputed" | "resolved";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    upload_file_api_v1_files_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_files_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_files_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_files_api_v1_files_delete: {
        parameters: {
            query?: {
                status_filter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_v1_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_v1_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_dates_api_v1_files__file_id__dates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_data_directory_api_v1_files_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_scan_status_api_v1_files_scan_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_watcher_status_api_v1_files_watcher_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_activity_data_api_v1_activity__file_id___analysis_date__get: {
        parameters: {
            query?: {
                /** @description Hours of data to return (12-48) */
                view_hours?: number;
            };
            header?: never;
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_data_with_sadeh_api_v1_activity__file_id___analysis_date__sadeh_get: {
        parameters: {
            query?: {
                view_hours?: number;
            };
            header?: never;
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_markers_api_v1_markers__file_id___analysis_date__get: {
        parameters: {
            query?: {
                /** @description Include Sadeh algorithm results */
                include_algorithm?: boolean;
            };
            header?: never;
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkersWithMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_markers_api_v1_markers__file_id___analysis_date__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
                analysis_date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkerUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_marker_api_v1_markers__file_id___analysis_date___period_index__delete: {
        parameters: {
            query?: {
                marker_category?: components["schemas"]["MarkerCategory"];
            };
            header?: never;
            path: {
                file_id: number;
                analysis_date: string;
                period_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_onset_offset_data_api_v1_markers__file_id___analysis_date__table__period_index__get: {
        parameters: {
            query?: {
                window_minutes?: number;
            };
            header?: never;
            path: {
                file_id: number;
                analysis_date: string;
                period_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnsetOffsetTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
